language: php

php:
#  - 7.0
  - 7.1
#  - hhvm
  - nightly

install:
  - composer install

script:
  - vendor/bin/phpunit -c build

after_script:
  - composer require php-coveralls/php-coveralls
  - php vendor/bin/coveralls -v
